[ { id: 1, ranking: '574', word: 'absoluto', type: 'adj' },
  { id: 2, ranking: '676', word: 'actual', type: 'adj' },
  { id: 3, ranking: '948', word: 'adecuado', type: 'adj' },
  { id: 4, ranking: '963', word: 'alemán', type: 'adj' },
  { id: 5, ranking: '763', word: 'amplio', type: 'adj' },
  { id: 6, ranking: '904', word: 'azul', type: 'adj' },
  { id: 7, ranking: '942', word: 'cercano', type: 'adj' },
  { id: 8, ranking: '680', word: 'cerrado', type: 'adj' },
  { id: 9, ranking: '774', word: 'civil', type: 'adj' },
  { id: 10, ranking: '909', word: 'concreto', type: 'adj' },
  { id: 11, ranking: '540', word: 'conocido', type: 'adj' },
  { id: 12, ranking: '838', word: 'corriente', type: 'adj' },
  { id: 13, ranking: '537', word: 'corto', type: 'adj' },
  { id: 14, ranking: '723', word: 'cuánto', type: 'adj' },
  { id: 15, ranking: '655', word: 'cuarto', type: 'adj' },
  { id: 16, ranking: '968', word: 'dado', type: 'adj' },
  { id: 17, ranking: '981', word: 'debido:', type: 'adj' },
  { id: 18, ranking: '803', word: 'definitivo', type: 'adj' },
  { id: 19, ranking: '927', word: 'determinado', type: 'adj' },
  { id: 20, ranking: '903', word: 'diario', type: 'adj' },
  { id: 21, ranking: '733', word: 'directo', type: 'adj' },
  { id: 22, ranking: '690', word: 'dispuesto', type: 'adj' },
  { id: 23, ranking: '740', word: 'diverso', type: 'adj' },
  { id: 24, ranking: '615', word: 'duro', type: 'adj' },
  { id: 25, ranking: '698', word: 'enfermo', type: 'adj' },
  { id: 26, ranking: '760', word: 'entero', type: 'adj' },
  { id: 27, ranking: '879', word: 'exacto', type: 'adj' },
  { id: 28, ranking: '551', word: 'extraño', type: 'adj' },
  { id: 29, ranking: '860', word: 'extraordinario', type: 'adj' },
  { id: 30, ranking: '514', word: 'fácil', type: 'adj' },
  { id: 31, ranking: '744', word: 'familiar', type: 'adj' },
  { id: 32, ranking: '713', word: 'famoso', type: 'adj' },
  { id: 33, ranking: '956', word: 'feliz', type: 'adj' },
  { id: 34, ranking: '643', word: 'físico', type: 'adj' },
  { id: 35, ranking: '646', word: 'francés', type: 'adj' },
  { id: 36, ranking: '907', word: 'frío', type: 'adj' },
  { id: 37, ranking: '623', word: 'futuro', type: 'adj' },
  { id: 38, ranking: '548', word: 'grave', type: 'adj' },
  { id: 39, ranking: '980', word: 'histórico', type: 'adj' },
  { id: 40, ranking: '592', word: 'imposible', type: 'adj' },
  { id: 41, ranking: '608', word: 'inglés', type: 'adj' },
  { id: 42, ranking: '724', word: 'inmediato', type: 'adj' },
  { id: 43, ranking: '762', word: 'interesante', type: 'adj' },
  { id: 44, ranking: '614', word: 'interior', type: 'adj' },
  { id: 45, ranking: '783', word: 'interno', type: 'adj' },
  { id: 46, ranking: '953', word: 'italiano', type: 'adj' },
  { id: 47, ranking: '915', word: 'justo', type: 'adj' },
  { id: 48, ranking: '508', word: 'lleno', type: 'adj' },
  { id: 49, ranking: '961', word: 'maestro', type: 'adj' },
  { id: 50, ranking: '777', word: 'mas', type: 'adj' },
  { id: 51, ranking: '656', word: 'material', type: 'adj' },
  { id: 52, ranking: '564', word: 'médico', type: 'adj' },
  { id: 53, ranking: '856', word: 'militar', type: 'adj' },
  { id: 54, ranking: '990', word: 'mínimo', type: 'adj' },
  { id: 55, ranking: '671', word: 'moderno', type: 'adj' },
  { id: 56, ranking: '687', word: 'muerto', type: 'adj' },
  { id: 57, ranking: '507', word: 'nacional', type: 'adj' },
  { id: 58, ranking: '664', word: 'normal', type: 'adj' },
  { id: 59, ranking: '888', word: 'oscuro', type: 'adj' },
  { id: 60, ranking: '837', word: 'parecido', type: 'adj' },
  { id: 61, ranking: '854', word: 'particular', type: 'adj' },
  { id: 62, ranking: '866', word: 'peor', type: 'adj' },
  { id: 63, ranking: '931', word: 'perdido', type: 'adj' },
  { id: 64, ranking: '810', word: 'perfecto', type: 'adj' },
  { id: 65, ranking: '590', word: 'personal', type: 'adj' },
  { id: 66, ranking: '875', word: 'plano', type: 'adj' },
  { id: 67, ranking: '679', word: 'pleno', type: 'adj' },
  { id: 68, ranking: '709', word: 'popular', type: 'adj' },
  { id: 69, ranking: '739', word: 'preciso', type: 'adj' },
  { id: 70, ranking: '802', word: 'presente', type: 'adj' },
  { id: 71, ranking: '706', word: 'privado', type: 'adj' },
  { id: 72, ranking: '640', word: 'profesional', type: 'adj' },
  { id: 73, ranking: '637', word: 'puro', type: 'adj' },
  { id: 74, ranking: '652', word: 'rápido', type: 'adj' },
  { id: 75, ranking: '849', word: 'raro', type: 'adj' },
  { id: 76, ranking: '886', word: 'religioso', type: 'adj' },
  { id: 77, ranking: '955', word: 'responsable', type: 'adj' },
  { id: 78, ranking: '627', word: 'rico', type: 'adj' },
  { id: 79, ranking: '533', word: 'rojo', type: 'adj' },
  { id: 80, ranking: '922', word: 'sencillo', type: 'adj' },
  { id: 81, ranking: '545', word: 'serio', type: 'adj' },
  { id: 82, ranking: '661', word: 'simple', type: 'adj' },
  { id: 83, ranking: '547', word: 'suficiente', type: 'adj' },
  { id: 84, ranking: '535', word: 'superior', type: 'adj' },
  { id: 85, ranking: '511', word: 'supuesto', type: 'adj' },
  { id: 86, ranking: '629', word: 'total', type: 'adj' },
  { id: 87, ranking: '858', word: 'unido', type: 'adj' },
  { id: 88, ranking: '878', word: 'verde', type: 'adj' },
  { id: 89, ranking: '631', word: 'abajo', type: 'adv' },
  { id: 90, ranking: '516', word: 'adelante', type: 'adv' },
  { id: 91, ranking: '556', word: 'alrededor', type: 'adv' },
  { id: 92, ranking: '587', word: 'apenas', type: 'adv' },
  { id: 93, ranking: '544', word: 'arriba', type: 'adv' },
  { id: 94, ranking: '843', word: 'aun', type: 'adv' },
  { id: 95, ranking: '869', word: 'completamente', type: 'adv' },
  { id: 96, ranking: '820', word: 'debajo', type: 'adv' },
  { id: 97, ranking: '885', word: 'delante', type: 'adv' },
  { id: 98, ranking: '701', word: 'detrás', type: 'adv' },
  { id: 99, ranking: '936', word: 'directamente', type: 'adv' },
  { id: 100, ranking: '684', word: 'especialmente', type: 'adv' },
]


// English below




[ { id: 1, ranking: '574', en_word: 'absolute', type: 'adj' },
  { id: 2, ranking: '676', en_word: 'current (adj)', type: 'adj' },
  { id: 3,
    ranking: '948',
    en_word: 'adequate, suitable',
    type: 'adj' },
  { id: 4, ranking: '963', en_word: 'German', type: 'adj' },
  { id: 5,
    ranking: '763',
    en_word: 'wide, ample, broad',
    type: 'adj' },
  { id: 6, ranking: '904', en_word: 'blue', type: 'adj' },
  { id: 7, ranking: '942', en_word: 'near', type: 'adj' },
  { id: 8, ranking: '680', en_word: 'closed', type: 'adj' },
  { id: 9, ranking: '774', en_word: 'civil (adj)', type: 'adj' },
  { id: 10, ranking: '909', en_word: 'concrete, real', type: 'adj' },
  { id: 11,
    ranking: '540',
    en_word: 'known, wellknown',
    type: 'adj' },
  { id: 12,
    ranking: '838',
    en_word: 'current, flow (nf)',
    type: 'adj' },
  { id: 13, ranking: '537', en_word: 'short, brief', type: 'adj' },
  { id: 14, ranking: '723', en_word: 'how much?', type: 'adj' },
  { id: 15,
    ranking: '655',
    en_word: 'room, chamber (nm)',
    type: 'adj' },
  { id: 16, ranking: '968', en_word: 'given', type: 'adj' },
  { id: 17, ranking: '981', en_word: 'due to', type: 'adj' },
  { id: 18,
    ranking: '803',
    en_word: 'definitive, conclusive',
    type: 'adj' },
  { id: 19,
    ranking: '927',
    en_word: 'determined, fixed',
    type: 'adj' },
  { id: 20, ranking: '903', en_word: 'newspaper (nm)', type: 'adj' },
  { id: 21,
    ranking: '733',
    en_word: 'direct, straight',
    type: 'adj' },
  { id: 22, ranking: '690', en_word: 'willing, ready', type: 'adj' },
  { id: 23,
    ranking: '740',
    en_word: 'different, several, diverse',
    type: 'adj' },
  { id: 24, ranking: '615', en_word: 'hard (adj)', type: 'adj' },
  { id: 25, ranking: '698', en_word: 'ill, sick', type: 'adj' },
  { id: 26,
    ranking: '760',
    en_word: 'entire, whole, complete',
    type: 'adj' },
  { id: 27,
    ranking: '879',
    en_word: 'exact, faithful, true',
    type: 'adj' },
  { id: 28,
    ranking: '551',
    en_word: 'strange, foreign',
    type: 'adj' },
  { id: 29,
    ranking: '860',
    en_word: 'extraordinary, exceptional',
    type: 'adj' },
  { id: 30, ranking: '514', en_word: 'easy', type: 'adj' },
  { id: 31,
    ranking: '744',
    en_word: 'familiar, of the family (adj)',
    type: 'adj' },
  { id: 32,
    ranking: '713',
    en_word: 'famous, wellknown',
    type: 'adj' },
  { id: 33,
    ranking: '956',
    en_word: 'happy, fortunate',
    type: 'adj' },
  { id: 34, ranking: '643', en_word: 'physical (adj)', type: 'adj' },
  { id: 35, ranking: '646', en_word: 'French', type: 'adj' },
  { id: 36, ranking: '907', en_word: 'cold (adj)', type: 'adj' },
  { id: 37, ranking: '623', en_word: 'future (nm)', type: 'adj' },
  { id: 38,
    ranking: '548',
    en_word: 'serious, solemn',
    type: 'adj' },
  { id: 39, ranking: '980', en_word: 'historical', type: 'adj' },
  { id: 40, ranking: '592', en_word: 'impossible', type: 'adj' },
  { id: 41, ranking: '608', en_word: 'English', type: 'adj' },
  { id: 42, ranking: '724', en_word: 'immediate', type: 'adj' },
  { id: 43, ranking: '762', en_word: 'interesting', type: 'adj' },
  { id: 44,
    ranking: '614',
    en_word: 'interior, inside (nm)',
    type: 'adj' },
  { id: 45, ranking: '783', en_word: 'internal', type: 'adj' },
  { id: 46, ranking: '953', en_word: 'Italian', type: 'adj' },
  { id: 47, ranking: '915', en_word: 'just (adv)', type: 'adj' },
  { id: 48, ranking: '508', en_word: 'full, filled (as an object would de filled)', type: 'adj' },
  { id: 49,ranking: '961',en_word: 'teacher (m), master (nm)',type: 'adj' },
  { id: 50, ranking: '777', en_word: 'but, however', type: 'adj' },
  { id: 51,
    ranking: '656',
    en_word: 'material, element (nm)',
    type: 'adj' },
  { id: 52, ranking: '564', en_word: 'doctor (nm/f)', type: 'adj' },
  { id: 53, ranking: '856', en_word: 'military (adj)', type: 'adj' },
  { id: 54, ranking: '990', en_word: 'minimum (adj)', type: 'adj' },
  { id: 55, ranking: '671', en_word: 'modern', type: 'adj' },
  { id: 56, ranking: '687', en_word: 'dead (adj)', type: 'adj' },
  { id: 57, ranking: '507', en_word: 'national', type: 'adj' },
  { id: 58,
    ranking: '664',
    en_word: 'normal, usual, regular',
    type: 'adj' },
  { id: 59, ranking: '888', en_word: 'dark, obscure', type: 'adj' },
  { id: 60,
    ranking: '837',
    en_word: 'similar [also similar]',
    type: 'adj' },
  { id: 61,
    ranking: '854',
    en_word: 'particular, peculiar (adj)',
    type: 'adj' },
  { id: 62, ranking: '866', en_word: 'worse (adv)', type: 'adj' },
  { id: 63, ranking: '931', en_word: 'lost', type: 'adj' },
  { id: 64, ranking: '810', en_word: 'perfect', type: 'adj' },
  { id: 65, ranking: '590', en_word: 'personal (adj)', type: 'adj' },
  { id: 66,
    ranking: '875',
    en_word: 'plane, map, level (nm)',
    type: 'adj' },
  { id: 67,
    ranking: '679',
    en_word: 'complete, fulfilled (as emotionally)',
    type: 'adj' },
  { id: 68, ranking: '709', en_word: 'popular', type: 'adj' },
  { id: 69,
    ranking: '739',
    en_word: 'precise, necessary',
    type: 'adj' },
  { id: 70, ranking: '802', en_word: 'present (nm)', type: 'adj' },
  { id: 71, ranking: '706', en_word: 'private', type: 'adj' },
  { id: 72, ranking: '640', en_word: 'professional', type: 'adj' },
  { id: 73, ranking: '637', en_word: 'pure, clean', type: 'adj' },
  { id: 74, ranking: '652', en_word: 'quick, fast', type: 'adj' },
  { id: 75,
    ranking: '849',
    en_word: 'strange, rare, scarce',
    type: 'adj' },
  { id: 76, ranking: '886', en_word: 'religious', type: 'adj' },
  { id: 77, ranking: '955', en_word: 'responsible', type: 'adj' },
  { id: 78, ranking: '627', en_word: 'rich, tasty', type: 'adj' },
  { id: 79, ranking: '533', en_word: 'red', type: 'adj' },
  { id: 80,
    ranking: '922',
    en_word: 'simple, plain, easy',
    type: 'adj' },
  { id: 81, ranking: '545', en_word: 'serious', type: 'adj' },
  { id: 82,
    ranking: '661',
    en_word: 'simple, mere, simpleminded',
    type: 'adj' },
  { id: 83,
    ranking: '547',
    en_word: 'sufficient, enough',
    type: 'adj' },
  { id: 84,
    ranking: '535',
    en_word: 'superior, upper',
    type: 'adj' },
  { id: 85,
    ranking: '511',
    en_word: 'supposed: of course',
    type: 'adj' },
  { id: 86,
    ranking: '629',
    en_word: 'total, entire (adj)',
    type: 'adj' },
  { id: 87, ranking: '858', en_word: 'united', type: 'adj' },
  { id: 88, ranking: '878', en_word: 'green', type: 'adj' },
  { id: 89,
    ranking: '631',
    en_word: 'down, below, downward',
    type: 'adv' },
  { id: 90,
    ranking: '516',
    en_word: 'forward, further',
    type: 'adv' },
  { id: 91,
    ranking: '556',
    en_word: 'about, around, round (adv)',
    type: 'adv' },
  { id: 92, ranking: '587', en_word: 'hardly, barely', type: 'adv' },
  { id: 93, ranking: '544', en_word: 'up above', type: 'adv' },
  { id: 94,
    ranking: '843',
    en_word: 'even (though), still',
    type: 'adv' },
  { id: 95, ranking: '869', en_word: 'completely', type: 'adv' },
  { id: 96,
    ranking: '820',
    en_word: 'underneath, below',
    type: 'adv' },
  { id: 97,
    ranking: '885',
    en_word: 'in front of, ahead',
    type: 'adv' },
  { id: 98, ranking: '701', en_word: 'in the back', type: 'adv' },
  { id: 99,
    ranking: '936',
    en_word: 'directly, straight away',
    type: 'adv' },
  { id: 100, ranking: '684', en_word: 'especially', type: 'adv' }