let string = `
abilidad    ability
abnormalidad abnormality
accesibilidad accessibility
aceptabilidad acceptability
actividad activity
adaptabilidad adaptability
adversidad adversity
afinidad affinity
agilidad agility
agresividad aggressively
amenidad amenity
anbiguedad ambiguity
animosidad animosity
ansiedad anxiety
anualidad annuity
aplicabilidad applicability
artificialidad artificiality
atrocidad atrocity
autenticidad autenticity
autoridad authority
barbaridad barbarity
brevedad brevity
brutalidad brutality
calamidad calamity
calidad quality
capacidad capacity
celebridad celebrity
ciudad city
civilidad civility
claridad clarity
comodidad commodity
compatabilidad computability
comunidad community
conformidad conformity
continuidad continuity
creatividad creativity
credibilidad credibility
cristianidad Christianity
cruelidad cruelty
curiosidad curiosity
debilidad debility
deformidad deformity
densidad density
difficultidad difficulty
dignidad dignity
dishonestidad dishonesty
disparidad disparity
diversidad diversity
divinidad divinity
domesticidad domesticity
dualidad duality
duplicidad duplicity
durabilidad durability
elasticidad elasticity
electricidad electricity
elegibilidad eligibility
enormidad enormity
entidad entity
equidad equity
especialidad specialty
espiritualidad spirituality
espontaneidad spontaneity
estabilidad stability
esterilidad sterility
eternidad eternity
eventualidad eventuality
exclusividad exclusivity
expresividad expressively
extremidad extremity
falibilidad fallibility
familiaridad familiarity
fatalidad fatality
felicidad felicity
femininidad femininity
ferocidad ferocity
fertilidad fertility
festividad festivity
fidelidad fidelity
finalidad finality
flexibilidad flexibility
formalidad formality
fragilidad fragility
fraternidad fraternity
frugalidad frugality
funcionalidad functionality
generosidad generosity
gereralidad generality
gravedad gravity
heterosexualidad heterosexuality
hilaridad hilarity
hiperactividad hyperactivity
homosexualidad homosexuality
honestidad honesty
hospitalidad hospitality
hostilidad hostility
humanidad humanity
humilidad humility
identidad identity
igualidad equality
ilegalidad illegality
ilegibilidad illegibility
imparcialidad impartiality
imposibilidad impossibility
improbabilidad improbability
impropiedad impropriety
inactividad inactivity
incapacidad incapacity
incompatabilidad incompatibility
inconformidad unconformity
incredulidad incredulity
indignidad indignity
individualidad individuality
inevitabilidad inevitability
infalibilidad infallibility
inferioridad inferiority
infertilidad infertility
infidelidad infidelity
infinidad infinity
inflexibilidad inflexibility
informalidad informality
inmensidad immensity
inmortalidad immortality
inmunidad immunity
inseguridad insecurity
insinceridad insincerity
integridad integrity
intensidad intensity
intolerabilidad intolerability
invisibilidad invisibility
invulnerabilidad invulnerability
irracionalidad irrationality
irregularidad irregularity
irresponsibilidad irresponsibility
legalidad legality
legibilidad legibility
localidad locality
longevidad longevity
magnanimidad magnanimity
maleabilidad malleability
marginalidad marginality
masculinidad masculinity
maternidad maternity
mediocridad mediocrity
mentalidad mentality
modalidad modality
modernidad modernity
monstruosidad monstrosity
moralidad morality
mortalidad mortality
municipalidad municipality
necesidad necessity
negatividad negativity
neutralidad neutrality
normalidad normality
notoriedad notoriety
novedad novelty
obesidad obesity
objectividad objectivity
obscenidad obscenity
obscuridad obscurity
oportunidad opportunity
originalidad originality
paridad parity
paternidad paternity
peculiaridad peculiarity
perpetuidad perpetuity
personalidad personality
perversidad perversity
piedad piety
pluralidad plurality
polaridad polarity
popularidad popularity
posibilidad possibility
posteridad posterity
prioridad priority
probabilidad probability
productividad productivity
profundidad profundity
promiscuidad promiscuity
propiedad propriety
prosperidad prosperity
proximidad proximity
publicidad publicity
puntualidad punctuality
racionalidad rationality
realidad reality
regularidad regularity
relatividad relativity
respetabilidad respectability
responsabilidad responsibility
securidad security
selectividad selectivity
senilidad senility
sensibilidad sensibility
sensualidad sensuality
serenidad serenity
severidad severity
sexualidad sexuality
simplicidad simplicity
sinceridad sincerity
singularidad singularity
sobriedad sobriety
sociedad society
solidaridad solidarity
subjetividad subjectivity
superficialidad superficiality
superioridad superiority
tenacidad tenacity
tonalidad tonality
totalidad totality
tranquilidad tranquility
trinidad trinity
trivialidad triviality
unidad unity
uniformidad uniformity
universidad university
vanidad vanity
variedad variety
velocidad velocity
versatilidad versatility
viabilidad viability
virginidad virginity
virilidad virility
visabilidad visibility
viscosidad viscosity
vitalidad vitality
vivacidad vivacity
volatilidad volatility
voracidad voracity
vulgaridad vulgarity
abreviar abbreviate
acelerar accelerate
activar activate
acumular accumulate
administrar administrate
afiliar affiliate
agitar agitate
agravar aggravate
agregar aggregate
alienar alienate
altercar altercate
alternar alternate
amputar amputate
animar animate
anticipar anticipate
apreciar appreciate
aproximar approximate
articular articulate
asasinar assassinate
asfixiar asphyxiate
asimilar assimilate
asimilar assimilate
asociar associate
autenticar authenticate
calcular calculate
castigar castigate
castrar castrate
celebrar celebrate
circular circulate
coagular coagulate
colaborar collaborate
compensar compensate
complicar complicate
comunicar communicate
concentrar concentrate
confiscar confiscate
congratular congratulate
congregar congregate
conjugar conjugate
consolidar consolidate
contaminar contaminate
co-operar co-operate
coordinar coordinate
corroborar corroborate
crear create
culminar culminate
cultivar cultivate
debilitar debilitate
decapitar decapitate
decorar decorate
dedicar dedicate
degenerar degenerate
delegar delegate
deliberar deliberate
delinear delineate
demostrar demonstrate
denigrar denigrate
denunciar denunciate
depreciar depreciate
derivar derive
designar designate
desolar desolate
deteriorar deteriorate
devastar devastate
dictar dictate
diferenciar differentiate
dilatar dilate
discriminar discriminate
diseminar disseminate
dislocar dislocate
domesticar domesticate
dominar dominate
donar donate
duplicar duplicate
educar educate
elaborar elaborate
eliminar eliminate
emanar emanate
emancipar emancipate
emascular emasculate
emigrar emigrate
enumerar enumerate
enunciar enunciate
equivocar equivocate
especular speculate
estimar estimate
estimular stimulate
estrangular strangulate
evacuar evacuate
evaporar evaporate
exagerar exaggerate
exasperar exasperate
excavar excavate
exfoliar exfoliate
exonerar exonerate
expatriar expatriate
exterminar exterminate
fabricar fabricate
facilitar facilitate
fascinar fascinate
filtrar filtrate
fluctuar fluctuate
formular formulate
fornicar fornicate
frustrar frustrate
fumigar fumigate
generar generate
gesticular gesticulate
graduar graduate
habituar habituate
hesitar hesitate
humillar humiliate
iluminar illuminate
imitar imitate
implicar implicate
inaugurar inaugurate
incinerar incinerate
incorporar incorporate
incriminar incriminate
incubar incubate
indicar indicate
infatuar infatuate
infiltrar infiltrate
inflar inflate
iniciar initiate
inmigrar immigrate
innovar innovate
inocular inoculate
insinuar insinuate
instigar instigate
insular insulate
interrogar interrogate
intimidar intimidate
intoxicar intoxicate
intoxicar intoxicate
investigar investigate
irradiar irradiate
irrigar irrigate
irritar irritate
lacerar lacerate
liberar liberate
liquidar liquidate
litigar litigate
lubricar lubricate
manipular manipulate
masticar masticate
medicar medicate
meditar meditate
menstruar menstruate
moderar moderate
motivar motivate
mutilar mutilate
narrar narrate
navegar navigate
necesitar necessitate
negar negate
negociar negotiate
nominar nominate
obligar obligate
originar originate
orquestar orchestrate
oscilar oscillate
oxigenar oxygenate
palpar palpate
participar participate
penetrar penetrate
perforar perforate
perpetuar perpetuate
postular postulate
postular postulate
precipitar precipitate
predicar predicate
predominar predominate
premeditar premeditate
proliferar proliferate
pronosticar prognosticate
propagar propagate
radiar radiate
reciprocar reciprocate
recuperar recuperate
refrigerar refrigerate
regenerar regenerate
regular regulate
regurgitar regurgitate
rehabilitar rehabilitate
reiterar reiterate
relegar relegate
remunerar remunerate
renovar renovate
repatriar repatriate
resucitar resuscitate
revalidar revalidate
saturar saturate
segregar segregate
separar separate
sincopar syncopate
sindicar syndicate
situar situate
subordinar subordinate
substanciar substantiate
terminar terminate
tolerar tolerate
triangular triangulate
vacilar vacillate
validar validate
vegetar vegetate
ventilar ventilate
vibrar vibrate
vindicar vindicate
violar violate
`


let regex = /([a-zA-Z-_0-9]+)\s+([a-zA-Z-_0-9]+)\b/g;

parseString = function parseString(string) {
    let obj = [];
    while (temp = regex.exec(string)) {
        obj.push({
            es_word: temp[1],
            en_word: temp[2],
        });
    }

    return JSON.stringify(obj);
};
